### ISSUE TITLE
Does this support tramp?

### ISSUE THREAD

**Issue by lakkiy** [s-kostyaev/flymake-go-staticcheck#4]
No effect when editing remote file with tramp but worked at local, I also try M-x shell on remote buffer and check that staticcheck command exist.

**Comment by s-kostyaev** [comment]
I don't have tramp support added. For now I don't use this package, I use integration between gopls and staticcheck instead. You can try it out.

**Comment by s-kostyaev** [comment]
Also, this will work out of the box:
`M-x` `project-compile` `RET` `staticcheck ./...` `RET`
